### PR TITLE
fixes: use cache.ped, notify, convar locale switch, convert commands to ox_lib

### PR DESCRIPTION
**Pull request by buddizer**
## Description

- Use ox_lib cache.ped
- Convert notifies back to Notify
- Add convar locale switch
- Convert commands to ox_lib

## Checklist

- [x] I have personally loaded this code into an updated Qbox project and checked all of its functionality.
- [x] My code fits the style guidelines.
- [x] My PR fits the contribution guidelines.

### CODE REVIEW

**Comment by TonybynMp4** [comment]
Don't convert to notifyV2

**Comment by buddizer** [comment]
> Don't convert to notifyV2

Already reverted to Notify

**Comment by TonybynMp4** [comment]
> > Don't convert to notifyV2
> 
> Already reverted to Notify

careful tho the arguments are passed incorrectly

**Comment by buddizer** [comment]
> 

You are completely right, not sure why I put text =, the value goes directly...

**Comment by buddizer** [comment]
> > > Don't convert to notifyV2
> > 
> > 
> > Already reverted to Notify
> 
> careful tho the arguments are passed incorrectly

How so? description seems to have been replaced by text now, if you look at Chat's latest qbx-core changes

**Comment by TonybynMp4** [comment]
> > > > Don't convert to notifyV2
> > > 
> > > 
> > > Already reverted to Notify
> > 
> > 
> > careful tho the arguments are passed incorrectly
> 
> How so? description seems to have been replaced by text now, if you look at Chat's latest qbx-core changes

it's either {text = '', caption = ''} or it's like it's always been, in your case there's no point in using the table form since you only send the text

**Comment by TonybynMp4** [comment]
still not 😭 it's Notify(text, type, duration) it didn't change lol

**Comment by TonybynMp4** [comment]
Amen

**Pull request merged**
